    location /MYPATH {
        uwsgi_pass 127.0.0.1:4080;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param CF-Connecting-IP $remote_addr;
        uwsgi_param SCRIPT_NAME /MYPATH;
        include uwsgi_params;
    }
